### PR TITLE
Feature/junit5

### PR DESCRIPTION
**Pull request by jweiser**
Updates unit testing to use JUnit 5 and adds a log4j configuration to disable logging for unit tests.

All tests passed and had no logging output when running `mvn clean test` locally.

### CODE REVIEW

**Review by cookersjs — APPROVED** [review]

**Comment by SolomonShorser-OICR** [comment]
Just curious: why switch to JUnit5?

**Comment by jweiser** [comment]
> Just curious: why switch to JUnit5?

Just trying to stay up to date.  JUnit5 is the most recent stable major version.  The only caveat is PowerMock hasn't updated to be compatible with it yet, so I'm only migrating projects that aren't using it as a dependency.  If we need to revert to JUnit4, the changes aren't hard.

**Comment by SolomonShorser-OICR** [comment]
PowerMock's compatibility issue has been the main reason I was avoiding upgrading. But if this project's tests don't require it then upgrading probably is OK.

**Review by SolomonShorser-OICR — APPROVED** [review]

**Comment by jweiser** [comment]
> PowerMock's compatibility issue has been the main reason I was avoiding upgrading. But if this project's tests don't require it then upgrading probably is OK.

Yeah, I made sure to leave anything using PowerMock at JUnit4 until the compatibility issue is addressed.

**Pull request merged**
