### PR TITLE
Biomodels SBML file downloaded

### PR DESCRIPTION
**Pull request by cookersjs**
Even though this file hasn't been modified since 2017, it was a good point that it should still be downloaded from the source

### CODE REVIEW

**Comment by SolomonShorser-OICR** [comment]
Now I'm wondering why was this code using the archived file in the first place?

**Comment by cookersjs** [comment]
> Now I'm wondering why was this code using the archived file in the first place?

I think what happened is when `biomodels` as a step was being converted to either Java or Jenkins, I saw that the file in the directory was from 2017 and so I just assumed it was something we'd kept for a while. It probably is inspired by the fact that OrthoStableIdHistory is run immediately before this step, which itself has a static file (stable_id_mapping.stored_data) that we use perpetually. 

In the end, it was an honest mistake by me

**Comment by SolomonShorser-OICR** [comment]
Has it been tested with the more current file?

**Comment by cookersjs** [comment]
> Has it been tested with the more current file?

Yep! I ran it yesterday and it all worked as expected

**Review by SolomonShorser-OICR — APPROVED** [review]

**Pull request merged**
